// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1a5ccVK1WZxpn9AJKgSy3Rf9XJaJEMA',
    appId: '1:178388385662:android:87aba6d51fd9bf464cbd2f',
    messagingSenderId: '178388385662',
    projectId: 'picblockchain',
    storageBucket: 'picblockchain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv7aHozuPWiqSAATfUEERJP6SJb9drnH8',
    appId: '1:178388385662:ios:284846882adc42d04cbd2f',
    messagingSenderId: '178388385662',
    projectId: 'picblockchain',
    storageBucket: 'picblockchain.appspot.com',
    androidClientId: '178388385662-9i0p9b3h7s2ooffa4ccnnkpe69r9kuvs.apps.googleusercontent.com',
    iosClientId: '178388385662-k1i518nnuf4thlf5pq6q71cnvhvmq9qc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pbc',
  );
}
